# Environment name which should equal to Git branch name
main:

  # SSH user to be used in deployment
  user: www-data

  # Server hostname or IP address for deployment
  hostname: wp-quangduxng.com
  
  # Path to deploy.
  deploy_path: /opt/easyengine/sites/prod.example.com/app/htdocs

# Another environment. You can have as many as possible
develop:
  user: www-data
  hostname: wp-quangduxng.com
  deploy_path: /opt/easyengine/sites/dev.example.com/app/htdocs
